name: clean_architecture
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  retrofit: ^4.4.1
  analyzer: ^6.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  device_info_plus: ^10.1.2
  logger: ^2.4.0
  get_it: ^8.0.0
  lottie: ^3.1.2
  country_code_picker: ^3.0.0
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

  flutter_lints: ^3.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/splash_logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
